# Generated by Django 4.2 on 2023-04-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('serial_number', models.IntegerField()),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='UID')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('image_path', models.TextField(verbose_name='caminho da imagem')),
                ('caliber', models.CharField(max_length=10, verbose_name='Calibre')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'ordering': ['name'],
            },
        ),
    ]
