# Generated by Django 4.2 on 2023-04-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('serial_number', models.IntegerField(verbose_name='Numero de serial')),
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='UID')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('image_path', models.TextField(verbose_name='caminho da imagem')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Equipamento',
            },
        ),
        migrations.CreateModel(
            name='Wearable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Calibre')),
                ('equipment_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Armament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(verbose_name='Modelo do armamento')),
                ('caliber', models.CharField(max_length=10, verbose_name='Calibre')),
                ('equipment_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
        ),
    ]
