# Generated by Django 4.2 on 2023-04-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearable',
            name='size',
            field=models.CharField(max_length=10, verbose_name='Tamanho'),
        ),
    ]
