# Generated by Django 4.2 on 2023-04-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_wearable_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armament_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('image_path', models.TextField(verbose_name='caminho da imagem')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('model', models.TextField(verbose_name='Modelo do armamento')),
            ],
        ),
        migrations.CreateModel(
            name='Wearble_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('image_path', models.TextField(verbose_name='caminho da imagem')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('size', models.TextField(verbose_name='Modelo do armamento')),
            ],
        ),
    ]
