# Generated by Django 4.2 on 2023-06-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_bullet_model_accessory_model_armament_model_grenada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Numero de série'),
        ),
    ]
