# Generated by Django 4.2 on 2023-04-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_armament_model_wearble_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='image_path',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.IntegerField(verbose_name='Numero de série'),
        ),
    ]
