# Generated by Django 4.2.3 on 2023-08-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_remove_equipment_accessory_remove_equipment_armament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='image_path',
            field=models.FileField(upload_to='Modelos/municoes/'),
        ),
        migrations.AlterField(
            model_name='model_accessory',
            name='image_path',
            field=models.FileField(upload_to='Modelos/acessorios/'),
        ),
        migrations.AlterField(
            model_name='model_armament',
            name='image_path',
            field=models.FileField(upload_to='Modelos/armamentos/'),
        ),
        migrations.AlterField(
            model_name='model_grenada',
            name='image_path',
            field=models.FileField(upload_to='Modelos/granadas/'),
        ),
        migrations.AlterField(
            model_name='model_wearable',
            name='image_path',
            field=models.FileField(upload_to='Modelos/vestiveis/'),
        ),
    ]
