# Generated by Django 4.2 on 2023-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_remove_equipment_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Armament_model',
        ),
        migrations.DeleteModel(
            name='Wearble_model',
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.RemoveField(
            model_name='armament',
            name='equipment_uid',
        ),
        migrations.RemoveField(
            model_name='wearable',
            name='equipment_uid',
        ),
        migrations.AddField(
            model_name='armament',
            name='description',
            field=models.CharField(default=None, max_length=500, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armament',
            name='image_path',
            field=models.TextField(default=None, verbose_name='caminho da imagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='type_id',
            field=models.IntegerField(default=None, verbose_name='ID_Tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wearable',
            name='description',
            field=models.CharField(default=None, max_length=500, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wearable',
            name='image_path',
            field=models.TextField(default=None, verbose_name='caminho da imagem'),
            preserve_default=False,
        ),
    ]
