# Generated by Django 4.2.3 on 2023-08-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_bullet_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='caliber',
            field=models.CharField(choices=[('', 'SELECIONE'), ('9mm', '9mm'), ('.45 ACP', '.45 ACP'), ('.380 ACP', '.380 ACP'), ('.40 S&W', '.40 S&W'), ('.357 Magnum', '.357 Magnum'), ('.44 Magnum', '.44 Magnum'), ('5.56mm', '5.56mm'), ('7.62mm', '7.62mm'), ('.22 LR', '.22 LR')], default='SELECIONE', max_length=30, verbose_name='Calibre'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('6H', '6H'), ('8H', '8H'), ('12H', '12H'), ('24H', '24H'), ('24H', '24H'), ('CONSERTO', 'CONSERTO'), ('INDETERMINADO', 'INDETERMINADO'), ('REQUISIÇÃO JUDICIAL', 'REQUISIÇÃO JUDICIAL')], default='Disponível', max_length=20, verbose_name='Estado atual'),
        ),
        migrations.AlterField(
            model_name='model_armament',
            name='caliber',
            field=models.CharField(choices=[('', 'SELECIONE'), ('9mm', '9mm'), ('.45 ACP', '.45 ACP'), ('.380 ACP', '.380 ACP'), ('.40 S&W', '.40 S&W'), ('.357 Magnum', '.357 Magnum'), ('.44 Magnum', '.44 Magnum'), ('5.56mm', '5.56mm'), ('7.62mm', '7.62mm'), ('.22 LR', '.22 LR')], default='SELECIONE', max_length=30, verbose_name='Calibre'),
        ),
    ]
