# Generated by Django 4.2.5 on 2023-09-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('equipment', '0006_alter_bullet_caliber_alter_equipment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='model_id',
            field=models.PositiveIntegerField(verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo do modelo'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('6H', '6H'), ('8H', '8H'), ('12H', '12H'), ('24H', '24H'), ('CONSERTO', 'CONSERTO'), ('INDETERMINADO', 'INDETERMINADO'), ('REQUISIÇÃO JUDICIAL', 'REQUISIÇÃO JUDICIAL')], default='Disponível', max_length=20, verbose_name='Estado atual'),
        ),
    ]
