# Generated by Django 4.2.5 on 2023-09-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_equipment_model_id_alter_equipment_model_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullet',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Ativado'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Ativado'),
        ),
        migrations.AddField(
            model_name='model_accessory',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Ativado'),
        ),
        migrations.AddField(
            model_name='model_armament',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Ativado'),
        ),
        migrations.AddField(
            model_name='model_grenada',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Ativado'),
        ),
        migrations.AddField(
            model_name='model_wearable',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Ativado'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Numero de série'),
        ),
    ]
