# Generated by Django 4.2 on 2023-06-04 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_bullet_grenada_model_accessory_model_armament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='type_id',
        ),
        migrations.AddField(
            model_name='bullet',
            name='description',
            field=models.TextField(default='Descrição aqui', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='accessory',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='equipment.model_accessory'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='armament',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='equipment.model_armament'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='wearable',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='equipment.model_wearable'),
        ),
        migrations.AddField(
            model_name='grenada',
            name='description',
            field=models.TextField(default='Descrição aqui', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_accessory',
            name='description',
            field=models.TextField(default='Descrição aqui', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_armament',
            name='description',
            field=models.TextField(default='Descrição aqui', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_wearable',
            name='description',
            field=models.TextField(default='Descrição aqui', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='observation',
            field=models.TextField(default=None, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='uid',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False, verbose_name='UID'),
        ),
    ]
