# Generated by Django 4.2 on 2023-06-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_remove_equipment_type_id_bullet_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='accessory',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.model_accessory'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='armament',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.model_armament'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='wearable',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.model_wearable'),
        ),
    ]
