# Generated by Django 4.2 on 2023-06-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_alter_equipment_accessory_alter_equipment_armament_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grenada',
            new_name='Model_grenada',
        ),
        migrations.AddField(
            model_name='equipment',
            name='grenada',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.model_grenada'),
        ),
        migrations.AddField(
            model_name='model_accessory',
            name='image_path',
            field=models.TextField(default='', verbose_name='caminho da imagem'),
        ),
    ]
