# Generated by Django 4.2 on 2023-06-09 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_remove_cargo_police_alter_cargo_date_cargo_and_more'),
        ('equipment', '0012_rename_grenada_model_grenada_equipment_grenada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cargo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo.cargo'),
        ),
    ]
