# Generated by Django 4.2 on 2023-06-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_equipment_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='cargo',
        ),
    ]
