# Generated by Django 4.2 on 2023-06-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_remove_equipment_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='observation',
            field=models.TextField(default='-', verbose_name='Observação'),
        ),
    ]
