# Generated by Django 4.2 on 2023-06-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_alter_equipment_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='uid',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False, verbose_name='uid'),
        ),
    ]
