# Generated by Django 4.2 on 2023-06-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_alter_equipment_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipamento'},
        ),
    ]
