# Generated by Django 4.2 on 2023-06-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_alter_equipment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='type',
        ),
    ]
