# Generated by Django 4.2 on 2023-06-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_remove_equipment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='observation',
        ),
    ]
# Generated by Django 4.2.1 on 2023-06-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_remove_equipment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='observation',
        ),
    ]
