# Generated by Django 4.2 on 2023-06-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_remove_equipment_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='Disponivel', max_length=20, verbose_name='Estado atual'),
        ),
    ]
