# Generated by Django 4.1.4 on 2023-05-23 17:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patent', models.CharField(max_length=100, verbose_name='Patente')),
                ('plate', models.CharField(max_length=20, verbose_name='Matricula')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterPolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=20)),
                ('posto', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('telefone', models.CharField(max_length=11)),
                ('lotacao', models.CharField(max_length=50)),
            ],
        ),
    ]
