# Generated by Django 4.2 on 2023-06-17 01:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patent', models.CharField(max_length=100, verbose_name='Patente')),
                ('plate', models.CharField(max_length=20, verbose_name='Matricula')),
                ('posto', models.CharField(default='Policial', max_length=10)),
                ('telefone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterPolice',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('plate', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('workplace', models.CharField(max_length=50, verbose_name='Local de trabalho')),
                ('graduation', models.CharField(max_length=10, verbose_name='Posto/graduação')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('photo', models.FileField(upload_to='media/', verbose_name='Foto')),
            ],
        ),
    ]
