# Generated by Django 4.2 on 2023-06-08 19:46

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('police_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='police.police')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('police.police',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='registerpolice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registerpolice',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='registerpolice',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='registerpolice',
            name='posto',
        ),
        migrations.RemoveField(
            model_name='registerpolice',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='registerpolice',
            name='telefone',
        ),
        migrations.AddField(
            model_name='police',
            name='posto',
            field=models.CharField(default='Policial', max_length=10),
        ),
        migrations.AddField(
            model_name='police',
            name='telefone',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
    ]
