# Generated by Django 4.2.1 on 2023-06-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerpolice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registerpolice',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='police',
            name='posto',
            field=models.CharField(default='Policial', max_length=10),
        ),
        migrations.AddField(
            model_name='police',
            name='telefone',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='foto',
            field=models.FileField(default=None, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerpolice',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registerpolice',
            name='matricula',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registerpolice',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registerpolice',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
