# Generated by Django 4.2 on 2023-06-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerpolice',
            name='graduation',
        ),
        migrations.RemoveField(
            model_name='registerpolice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registerpolice',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='registerpolice',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='registerpolice',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='registerpolice',
            name='workplace',
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='foto',
            field=models.FileField(default=None, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='lotacao',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='matricula',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='nome',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='posto',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='senha',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='telefone',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerpolice',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
