# Generated by Django 4.2.3 on 2023-08-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='image_path',
            field=models.FileField(upload_to='policiais/%Y/%m/%d/'),
        ),
    ]
