# Generated by Django 4.2 on 2023-05-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='police',
            options={},
        ),
        migrations.AlterModelManagers(
            name='police',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='police',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='police',
            name='email',
        ),
        migrations.RemoveField(
            model_name='police',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='police',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='police',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='police',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='police',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='police',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='police',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='police',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='police',
            name='username',
        ),
    ]
