# Generated by Django 4.2.3 on 2023-07-24 15:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('police', '0002_remove_registerpolice_graduation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunct',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=20)),
                ('lotacao', models.CharField(max_length=50)),
                ('posto', models.CharField(max_length=10)),
                ('foto', models.FileField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Police',
        ),
    ]
