# Generated by Django 4.2 on 2023-06-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_adjunto_remove_registerpolice_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adjunto',
        ),
    ]
