# Generated by Django 4.2.1 on 2023-05-20 20:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('police', '0002_alter_police_options_alter_police_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='police',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='police',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='police',
            name='id',
        ),
        migrations.RemoveField(
            model_name='police',
            name='name',
        ),
        migrations.RemoveField(
            model_name='police',
            name='password',
        ),
        migrations.AddField(
            model_name='police',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
