# Generated by Django 4.2 on 2023-06-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_remove_registerpolice_graduation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerpolice',
            name='senha',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
