# Generated by Django 4.2.5 on 2023-09-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_alter_police_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='image_path',
            field=models.FileField(upload_to='policiais/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='police',
            name='tipo',
            field=models.CharField(choices=[('Police', 'Policial'), ('Adjunct', 'Adjunto'), ('Admin', 'Admin')], default='Police', max_length=20),
        ),
    ]
