# Generated by Django 4.2 on 2023-06-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_registerpolice_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpolice',
            name='senha',
            field=models.CharField(max_length=50),
        ),
    ]
