# Generated by Django 4.2.3 on 2023-07-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_adjunct_delete_police'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjunct',
            name='nome',
            field=models.CharField(default='nome', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerpolice',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
