# Generated by Django 4.2.1 on 2023-06-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_delete_adjunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerpolice',
            name='id',
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='email',
            field=models.EmailField(default='xxxxxxxxx', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='img',
            field=models.ImageField(default='xxxxxxx', upload_to='img_police/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='matricula',
            field=models.CharField(default='xxxxxxxxxxx', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='nome',
            field=models.CharField(default='xxxxxxx', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='posto',
            field=models.CharField(default='Policial', max_length=10),
        ),
        migrations.AddField(
            model_name='registerpolice',
            name='telefone',
            field=models.CharField(default='xxxxxxxx', max_length=11),
            preserve_default=False,
        ),
    ]
