# Generated by Django 4.2.5 on 2023-09-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_alter_police_image_path_alter_police_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Ativado'),
        ),
    ]
