# Generated by Django 4.2.3 on 2023-08-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0004_adjunct_nome_alter_registerpolice_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerpolice',
            options={'verbose_name': 'Policial', 'verbose_name_plural': 'Policiais'},
        ),
        migrations.AlterField(
            model_name='adjunct',
            name='telefone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registerpolice',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registerpolice',
            name='telefone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
