# Generated by Django 4.2.1 on 2023-06-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0005_remove_registerpolice_img_registerpolice_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpolice',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
