# Generated by Django 4.2 on 2023-06-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0006_alter_registerpolice_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpolice',
            name='foto',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='registerpolice',
            name='posto',
            field=models.CharField(max_length=10),
        ),
    ]
