# Generated by Django 4.2 on 2023-06-19 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('police', '0002_remove_registerpolice_graduation_and_more'),
        ('equipment', '0002_bullet_model_accessory_model_armament_model_grenada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(default='Pendente', max_length=20, verbose_name='Situação da carga')),
                ('date_load', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_load_return_date', models.DateTimeField(null=True, verbose_name='Data Prevista de Devolução')),
                ('turn_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pendente', max_length=20, verbose_name='horário_carga')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.registerpolice')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default='1', null=True, verbose_name='Quantidade')),
                ('observation', models.TextField(default=None, null=True, verbose_name='Observação')),
                ('status', models.CharField(default='Aprovado', max_length=20, verbose_name='Status')),
                ('bullet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.bullet')),
                ('equipment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='load.load')),
            ],
        ),
    ]
