# Generated by Django 4.1.3 on 2023-05-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Numero de série')),
                ('type_equipment', models.CharField(max_length=50, verbose_name='Tipo')),
                ('caliber', models.CharField(max_length=10, verbose_name='Calibre')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('size', models.CharField(max_length=3, verbose_name='Tamanho')),
                ('note', models.TextField(max_length=250, verbose_name='Observação')),
            ],
        ),
    ]
