# Generated by Django 4.1.3 on 2023-06-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='situation',
        ),
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(default='Pendente', max_length=50, verbose_name='horário_carga'),
        ),
    ]
