# Generated by Django 4.2.3 on 2023-08-25 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('load', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='adjunct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adjunto', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='load',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policial', to=settings.AUTH_USER_MODEL),
        ),
    ]
