# Generated by Django 4.1.3 on 2023-06-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0002_remove_load_situation_alter_load_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='returned_load_date',
            field=models.DateTimeField(null=True, verbose_name='Data de Descarregamento'),
        ),
    ]
