# Generated by Django 4.2.5 on 2023-09-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0002_load_adjunct_alter_load_police'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_load',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_loads', to='load.load'),
        ),
        migrations.AlterField(
            model_name='equipment_load',
            name='status',
            field=models.CharField(choices=[('Devolvido', 'Devolvido'), ('Pendente', 'Pendente')], default='Pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('Devolvido', 'Devolvido'), ('Pendente', 'Pendente'), ('Parcialmente devolvido', 'Parcialmente devolvido')], default='DENTRO DO PRAZO', max_length=50, verbose_name='horário_carga'),
        ),
    ]
