# Generated by Django 4.2.3 on 2023-07-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0004_adjunct_nome_alter_registerpolice_nome'),
        ('load', '0003_load_returned_load_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='police.registerpolice'),
        ),
    ]
