# Generated by Django 4.1.3 on 2023-05-24 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cargo', models.DateTimeField(verbose_name='Data da Carga')),
                ('expected_cargo_return_date', models.DateTimeField(verbose_name='Data Prevista de Devolução')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.registerpolice')),
            ],
        ),
    ]
