# Generated by Django 4.2 on 2023-06-17 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_registerpolice_senha'),
        ('cargo', '0002_remove_cargo_police_cargo_situation_cargo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='police',
            field=models.OneToOneField(default='WA025ALM', on_delete=django.db.models.deletion.CASCADE, to='police.registerpolice'),
            preserve_default=False,
        ),
    ]
