# Generated by Django 4.2 on 2023-06-09 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_cargo_situation_cargo_status_alter_cargo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='police',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='date_cargo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(default='Pendente', max_length=20, verbose_name='horário_carga'),
        ),
    ]
