# Generated by Django 4.2 on 2023-06-19 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0005_alter_registerpolice_senha'),
        ('cargo', '0003_cargo_police'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.registerpolice'),
        ),
    ]
