# Generated by Django 4.2 on 2023-06-09 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_remove_equipment_cargo'),
        ('cargo', '0003_remove_cargo_police_alter_cargo_date_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet_amount', models.IntegerField(default=None, null=True, verbose_name='Quantidade_munição')),
                ('bullet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.bullet')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cargo.cargo')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.equipment')),
            ],
        ),
    ]
