# Generated by Django 4.2 on 2023-06-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_cargo_turn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='expected_cargo_return_date',
            field=models.DateTimeField(null=True, verbose_name='Data Prevista de Devolução'),
        ),
    ]
