# Generated by Django 4.2.1 on 2023-06-10 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_alter_equipment_uid'),
        ('cargo', '0005_alter_equipment_cargo_bullet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_cargo',
            name='bullet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.bullet'),
        ),
        migrations.AlterField(
            model_name='equipment_cargo',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment'),
        ),
    ]
