# Generated by Django 4.2 on 2023-06-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_alter_equipment_cargo_bullet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_cargo',
            name='bullet_amount',
        ),
        migrations.AddField(
            model_name='equipment_cargo',
            name='amount',
            field=models.IntegerField(default='1', null=True, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='equipment_cargo',
            name='observation',
            field=models.TextField(default=None, null=True, verbose_name='Observação'),
        ),
    ]
