# Generated by Django 4.2.1 on 2023-06-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_alter_equipment_cargo_bullet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_cargo',
            name='observation',
            field=models.TextField(default=None, null=True, verbose_name='Observação'),
        ),
    ]
