# Generated by Django 4.2 on 2023-06-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_equipment_cargo_observation'),
        ('cargo', '0008_alter_equipment_cargo_equipment'),
    ]

    operations = [
    ]
